services:
  article:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  photo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"