services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5172:5172"

  other:
    build:
      context: ./getOtherServicesData
      dockerfile: Dockerfile
    container_name: portfolio_other
    working_dir: /app
    volumes:
      - ./getOtherServicesData:/app
    ports:
      - "8001:8001"
      - "8002:8002"

networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local