services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5172:5172"

  article:
    build:
      context: ./getOtherServicesData
      dockerfile: getArticle/Dockerfile
    container_name: portfolio_article
    working_dir: /app/getOtherServicesData/getArticle
    volumes:
      - ./getOtherServicesData/getArticle:/app/getOtherServicesData/getArticle
    ports:
      - "8001:8000"

  photo:
    build:
      context: ./getOtherServicesData
      dockerfile: getPhoto/Dockerfile
    container_name: portfolio_photo
    working_dir: /app/getOtherServicesData/getPhoto
    volumes:
      - ./getOtherServicesData/getPhoto:/app/getOtherServicesData/getPhoto
    ports:
      - "8002:8000"

networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local